version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.1
    - 12.0.2
    - 12.0.3
    - 12.0.4
  - dependency-name: electron-log
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.3
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: "@craco/craco"
    versions:
    - 6.1.0
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
